Add nginx check plugin
tcpcloud/salt-formula-collectd pull request #24
Opened 2016-11-17 14:01 UTC by simonpasquier

2016-11-18 16:04 UTC, elemoine requested changes
Minor comment, otherwise looks good to me.

2016-11-18 16:04 UTC, elemoine commented on collectd/files/plugin/collectd_nginx_check.py
> +                self.url = node.values[0]
You may want to `break` when a node with a URL was found.

2016-11-18 16:29 UTC, simonpasquier commented on collectd/files/plugin/collectd_nginx_check.py
> +                self.url = node.values[0]
Done

2016-11-18 16:30 UTC, elemoine approved these changes

2016-11-21 09:05 UTC, SwannCroiset requested changes
Why not re-using the HTTPCheckPlugin ?

2016-11-21 09:05 UTC, SwannCroiset commented on collectd/files/plugin/collectd_nginx_check.py
> +            requests.get(self.url, timeout=5)
timeout is a base configuration (handled by base.Base) , you can use self.timeout in place to hardcoded value.

2016-11-21 09:05 UTC, SwannCroiset commented on collectd/files/plugin/collectd_nginx_check.py
> +            requests.get(self.url, timeout=5)
IIRC, the requests.get doesn't return necessary an exception, you have to check the HTTP return code

2016-11-21 14:39 UTC, simonpasquier commented on collectd/files/plugin/collectd_nginx_check.py
> +            requests.get(self.url, timeout=5)
TBH I've adapted the already existing Apache check plugin which indeed has all the shortcomings that you describe.

2016-11-21 14:45 UTC, simonpasquier commented
@SwannCroiset 

> Why not re-using the HTTPCheckPlugin ?

right now the data collected by HTTPCheckPlugin translate into check_local_endpoint metrics. Eventually it should be generic but this requires additional work.

2016-11-21 14:46 UTC, simonpasquier commented on collectd/files/plugin/collectd_nginx_check.py
> +            requests.get(self.url, timeout=5)
also I think it's fine for now that the plugin doesn't check the return code. As long as the server replies, the check metric can be OK.

2016-11-21 14:49 UTC, SwannCroiset approved these changes
ok lets merge it as is

2016-11-21 15:19 UTC, merged