Add Contrail Python modules
tcpcloud/salt-formula-collectd pull request #27
Opened 2016-11-23 07:46 UTC by obourdon

2016-11-23 07:46 UTC, cloudlab-autobuild commented
Can one of the admins verify this patch?

2016-11-23 08:26 UTC, elemoine commented on collectd/files/plugin/contrail_apis.py
> +                                state = self.state[name]
Or more concisely:

```py
state = self.state.get('name')
```

(`state` will be `None` if `self.state` does not have a key `name`).

2016-11-23 08:29 UTC, elemoine reviewed
I just added a minor. I'll let other comment as I am not a collectd plugin expert.

2016-11-23 10:02 UTC, simonpasquier requested changes

2016-11-23 10:02 UTC, simonpasquier commented on collectd/files/plugin/contrail_apis.py
> +#!/usr/bin/python
better to name this file collectd_contrail_api.py to avoid name clashing with 3rd-party Python modules.

2016-11-23 10:02 UTC, simonpasquier commented on collectd/files/plugin/contrail_apis.py
> +                yield {'type_instance': name, 'values': self.FAIL}
Better to raise base.CheckException(msg). See the RabbitMQ collectd plugin for instance.

2016-11-23 10:02 UTC, simonpasquier commented on collectd/files/plugin/contrail_apis.py
> +                            yield {'type_instance': name, 'values': count}
any metadata to be added to the metrics?

2016-11-23 16:01 UTC, obourdon commented on collectd/files/plugin/contrail_apis.py
> +                yield {'type_instance': name, 'values': self.FAIL}
Got it. Will do

2016-11-23 16:01 UTC, obourdon commented on collectd/files/plugin/contrail_apis.py
> +#!/usr/bin/python
Agreed

2016-11-23 16:01 UTC, obourdon commented on collectd/files/plugin/contrail_apis.py
> +                                state = self.state[name]
Sure will

2016-11-23 16:12 UTC, obourdon commented
@simonpasquier new version integrated comments
As agreed, we'll see later on if metadata are needed

2016-11-24 07:48 UTC, elemoine approved these changes

2016-11-24 10:50 UTC, simonpasquier approved these changes

2016-11-24 13:24 UTC, merged