Add Zookeeper collectd plugin
tcpcloud/salt-formula-collectd pull request #43
Opened 2016-12-13 07:52 UTC by obourdon

2016-12-13 07:52 UTC, cloudlab-autobuild commented
Can one of the admins verify this patch?

2016-12-13 08:40 UTC, simonpasquier requested changes

2016-12-13 08:40 UTC, simonpasquier commented on collectd/files/plugin/collectd_zookeeper.py
> +INTERVAL = 50
why?

2016-12-13 08:40 UTC, simonpasquier commented on collectd/files/plugin/collectd_zookeeper.py
> +"""
this comment can be removed

2016-12-13 08:40 UTC, simonpasquier commented on collectd/files/plugin/collectd_zookeeper.py
> +class ZooKeeperServer(object):
you probably want to use collectd_base.Base and make it work like the other collectd plugins.

2016-12-13 10:42 UTC, obourdon commented on collectd/files/plugin/collectd_zookeeper.py
> +"""
Ok will do

2016-12-13 10:42 UTC, obourdon commented on collectd/files/plugin/collectd_zookeeper.py
> +INTERVAL = 50
To comply with other plugins sampling interval instead of default 10s from /etc/collectd/collectd.conf

2016-12-13 10:42 UTC, obourdon commented on collectd/files/plugin/collectd_zookeeper.py
> +class ZooKeeperServer(object):
Ok will do and test before submitting new PR version

2016-12-15 09:56 UTC, simonpasquier commented on collectd/files/plugin/collectd_zookeeper.py
> +INTERVAL = 50
That's not the case for all the plugins. Only for those that are heavy-loading the monitored service.

2016-12-21 12:20 UTC, obourdon commented
@simonpasquier @thouveng please review latest version which integrates requested changes
Tested successfully on my deployed mk22 test environment

2016-12-21 12:21 UTC, obourdon commented
Oops forgot to run pep8 on final file. Will post updated version soon

2017-01-31 13:04 UTC, cloudlab-autobuild commented
Can one of the admins verify this patch?

2017-03-13 14:42 UTC, closed without merging