Limit collectd write queue memory
tcpcloud/salt-formula-collectd pull request #49
Opened 2017-01-12 13:11 UTC by SwannCroiset

2017-01-12 13:48 UTC, simonpasquier requested changes
I would add the parameters to map.jinja too so that everybody benefit from this fix.

2017-01-12 13:57 UTC, SwannCroiset commented
> I would add the parameters to map.jinja too so that everybody benefit from this fix.

I thought about yes but this will prevent to remove this queue limits if someone doesn't want them.
you mean other than MK deployment b/c here all MK deployments benefit of this fix w/ service metadata ?

2017-01-12 14:23 UTC, simonpasquier commented
It's probably not a good idea to let these parameters unset.

2017-01-17 10:37 UTC, simonpasquier approved these changes

2017-01-17 10:37 UTC, merged