Remote check support
tcpcloud/salt-formula-collectd pull request #7
Opened 2016-10-24 23:14 UTC by cznewt

2016-10-26 07:56 UTC, simonpasquier requested changes

2016-10-26 07:56 UTC, simonpasquier commented on collectd/files/collectd_python.conf
>    {%- include plugin.template %}
s/{%-/{%/ otherwise it generates an invalid configuration

`Interactive falseImport "rabbitmq_info"`

2016-10-26 07:56 UTC, simonpasquier commented on collectd/files/collectd_python.conf
> +  {%- include plugin.template %}
ditto

2016-10-27 08:42 UTC, simonpasquier requested changes

2016-10-27 08:42 UTC, simonpasquier commented on collectd/files/collectd_python.conf
>    {%- include plugin.template %}
@cznewt can you address my comments or do you want me to add a commit on top of it?

2016-10-27 14:31 UTC, SwannCroiset approved these changes
Lets fix later typos. Simon will fix them.

2016-10-27 14:31 UTC, merged